"""Storage subpackage for card database management."""

from kardscm.storage.backup import backup_database
from kardscm.storage.database import (
    ADMIN_DB_COLUMNS,
    ADMIN_EDITABLE_SCALARS,
    apply_extra_abilities_seed,
    delete_all_decks,
    delete_cards,
    delete_deck,
    delete_metadata,
    fetch_all_decks,
    fetch_cards,
    fetch_deck_cards,
    find_card_id,
    find_card_id_by_exile,
    find_deck_by_name,
    get_card_quantity_by_id,
    get_connection,
    get_metadata,
    initialize_schema,
    insert_deck,
    insert_deck_cards,
    set_metadata,
    update_card_admin,
    update_card_quantity_by_id,
    update_quantity,
    upsert_cards,
)

__all__ = [
    "ADMIN_DB_COLUMNS",
    "ADMIN_EDITABLE_SCALARS",
    "apply_extra_abilities_seed",
    "backup_database",
    "delete_all_decks",
    "delete_cards",
    "delete_deck",
    "delete_metadata",
    "fetch_all_decks",
    "fetch_cards",
    "fetch_deck_cards",
    "find_card_id",
    "find_card_id_by_exile",
    "find_deck_by_name",
    "get_card_quantity_by_id",
    "get_connection",
    "get_metadata",
    "initialize_schema",
    "insert_deck",
    "insert_deck_cards",
    "set_metadata",
    "update_card_admin",
    "update_card_quantity_by_id",
    "update_quantity",
    "upsert_cards",
]
